### ISSUE TITLE
I2C questions

### ISSUE THREAD

**Issue by Blisto91** [newAM/ftd2xx-embedded-hal#16]
Hi there.

Is the I2C implementation supposed to be working or is it still a bit too early?
My I2C circuit always seemed to reply with ack even when the power was off (using an ftdi calbe to talk with a seperate board) and then i started looking through the code a bit.
I noticed in the source things like ack's not getting handled.
Haven't looked at everything and have mostly toyed with the write function.

Like what you are doing so far and hope to replace my own hacky wrapper around libftd2xx-rs with this in the future.

Edit: Scratch the part about SDA not being driven high. That seems to have been my own fault.

**Comment by newAM** [comment]
> Is the I2C implementation supposed to be working or is it still a bit too early?

It should be working!  It works with the I2C BME280 crate in the README, and should be working for everything else too.  I'll mark this as a bug.

> I noticed in the source things like ack's not getting handled.

Oh no.  Where at?

Also you are using 0.5.1, right?  There were some bugs in 0.5.0 with I2C.

**Comment by Blisto91** [comment]
Ye was using 0.5.1 after that i started messing with main and modifying the example.

I'm thinking here
https://github.com/newAM/ftd2xx-embedded-hal/blob/ec5989549082aa39507c4eb4b311208864bddae1/src/i2c.rs#L140-L143
here
https://github.com/newAM/ftd2xx-embedded-hal/blob/ec5989549082aa39507c4eb4b311208864bddae1/src/i2c.rs#L198-L200
and  here
https://github.com/newAM/ftd2xx-embedded-hal/blob/ec5989549082aa39507c4eb4b311208864bddae1/src/i2c.rs#L300-L303
The ACK bits are read but they aren't ever verified to be 0x00.

Edit: Removed the part about read_all. I understand that part of the code now.

**Comment by newAM** [comment]
> The ACK bits are read but they aren't ever verified to be 0x00.

Ah, yeah, that is a problem.

I made a branch, `nak` with a potential fix, I added this to the end of the I2C trait implementations:
https://github.com/newAM/ftd2xx-embedded-hal/blob/5169c0d509476478089db9bcd2a52c178c2f326c/src/i2c.rs#L375-L382

This is a different implementation from `ftdi-embedded-hal` which does a device read after each slave ACK, and will end the transfer if the slave responds with a NAK.  The way `ftdi-embedded-hal` does it seems like the way most `embedded-hal` traits are implemented, but in the case of the D2XX drivers this slows things down a fair bit

Not sure if I should try to make this fit better with other HALs, or keep it performant.  Thoughts?

**Comment by Blisto91** [comment]
Awesome!
Won't be able to test it until I have my board and oscilloscope at work next week.

My thoughts are I that would expect the library to fail fast by default if no acks are received. If something is wrong with the I2C slave it would take a while to find out if i'm doing a large write with lots of bytes.
Tho I do understand your concern about slowdowns. 

I think your current current code is similar to the ``I2C_FastWrite`` & ``I2C_FastRead`` functions in [LIBMPSSE-I2C. ](https://ftdichip.com/software-examples/mpsse-projects/libmpsse-i2c-examples/) 
Maybe an option that can let the user toggle this behavior?

**Comment by newAM** [comment]
> Maybe an option that can let the user toggle this behavior?

I updated the branch, now with a `set_fast` (disabled by default) for switching between the two.
Works alright for my BME280, let me know if it solves any problems for you!

**Comment by Blisto91** [comment]
Coolio.
Will look through the code and test it out sometime next week.

Maybe I should have waited with my PR until after this was merged.

**Comment by Blisto91** [comment]
Now using an teensy to simulate a slave device so this can be tested at home. But I'm connecting it the same way as at work.
This seems to be working now and my ftdi cable recognizes missing acks from my slave when it is powered on.

It still wont complain when my slave device is turned off because it will see the 0V as the slave always sending an ack.
The two devices are powered separately and I have only synced ground between the devices. 
Dunno how common this scenario would be since I'm guessing VCC will mostly be synced in real applications.
Accidently bought the 5V VCC cable but the board at work use 3.3V so couldn't sync them up there. 
A work around for this could be to check for 0V on SCL before I attempt a write I guess.

**Comment by newAM** [comment]
> It still wont complain when my slave device is turned off because it will see the 0V as the slave always sending an ack. The two devices are powered separately and I have only synced ground between the devices.

Are there pull-up resistors present?  If there are situations were the slave will not be powered then there should be some on the master side.

**Comment by Blisto91** [comment]
[The ftdi cable](https://ftdichip.com/products/c232hm-edhsl-0/) doesn't have inbuilt pull ups since the pins are routed directly out to the wires and so relies on external resistors.
The way I've made it currently is just an adapter so it can be plugged directly into the external board.
The board have a lot of connectors and I envision using the same cable to enable debugging on each of them and user would just have to match up the colors on the cable and adapter.

Could maybe integrate some pull up scheme into this particular adapter.
Could also check if the cable can power the 3V3_init present on the board and just get the 3.3V VCC version instead of the current 5V.

**Comment by newAM** [comment]
Fixed in release [v0.7.0](https://github.com/newAM/ftd2xx-embedded-hal/tree/v0.7.0).

Thanks for the bug report and your help resolving it!
